# Pipeline to build and deploy controlDB for ELT Framework https://github.com/bennyaustin/elt-framework
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
  vmImage: windows-latest

steps:
- task: VSBuild@1
  inputs:
    solution: '**\ControlDB.sln'

- publish: $(System.DefaultWorkingDirectory)
  artifact: dacpac
  displayName: Publish Dacpac

- task: AzureKeyVault@2
  inputs:
    connectedServiceName: ba-devops-spn
    KeyVaultName: ba-keyvault1 
    SecretsFilter: ba-sqlserver1-sqlusername
    RunAsPreJob: true