# Pipeline to build and deploy controlDB for ELT Framework https://github.com/bennyaustin/elt-framework
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
- name: targetEnvironment
  displayName: Target Environment Name. Allowed values - prod/nonprod
  type: string
  default: nonprod

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
  vmImage: windows-latest

steps:
- ${{ if eq(parameters.targetEnvironment,'nonprod')}}:
  - template: azure-pipeline-parameters-db-nonprod.yml

- ${{ if eq(parameters.targetEnvironment,'prod')}}:
  - template: azure-pipeline-parameters-db-prod.yml

- task: VSBuild@1
  displayName: Build database project ${{parameters.dbSolutionName}}
  inputs:
    solution: '**\ControlDB.sln'

- publish: $(System.DefaultWorkingDirectory)
  artifact: dacpac
  displayName: Publish Dacpac

- task: AzureKeyVault@2
  displayName: Get keyvault secrets
  inputs:
    connectedServiceName: ba-devops-spn
    KeyVaultName: ba-keyvault1 
    SecretsFilter: ba-sqlserver1-sqlusername,ba-sqlserver1-password
    RunAsPreJob: true
- task: SqlAzureDacpacDeployment@1
  displayName: Deploy database
  inputs:
    ConnectedServiceNameARM: ba-devops-spn
    AuthenticationType: server
    ServerName: ba-sqlserver1.database.windows.net,1433
    DatabaseName: ControlDB
    SqlUsername: $(ba-sqlserver1-sqlusername)
    SqlPassword: $(ba-sqlserver1-password)
    DacpacFile: elt-framework\ControlDB\bin\Release\ControlDB.dacpac
    IpDetectionMethod: AutoDetect
    DeleteFirewallRule: true
    AdditionalArguments: /p:DropPermissionsNotInSource=false /p:DropRoleMembersNotInSource=false /p:DropObjectsNotInSource=true /p:IgnoreColumnOrder=true /p:IgnorePermissions=true