# Pipeline to build and deploy controlDB for ELT Framework https://github.com/bennyaustin/elt-framework
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
  vmImage: windows-latest

steps:
- task: VSBuild@1
  inputs:
    solution: '**\ControlDB.sln'

- publish: $(System.DefaultWorkingDirectory)
  artifact: dacpac
  displayName: Publish Dacpac

- task: AzureKeyVault@2
  inputs:
    connectedServiceName: ba-devops-spn
    KeyVaultName: ba-keyvault1 
    SecretsFilter: ba-sqlserver1-sqlusername,ba-sqlserver1-password
    RunAsPreJob: true
- task: SqlAzureDacpacDeployment@1
  inputs:
    ConnectedServiceNameARM: ba-devops-spn
    AuthenticationType: server
    ServerName: ba-sqlserver1.database.windows.net,1433
    DatabaseName: ControlDB
    SqlUsername: $(ba-sqlserver1-sqlusername)
    SqlPassword: $(ba-sqlserver1-password)
    DacpacFile: dacpac
    IpDetectionMethod: AutoDetect
    DeleteFirewallRule: true