# Pipeline to build and deploy controlDB for ELT Framework https://github.com/bennyaustin/elt-framework
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
  vmImage: windows-latest

stages:
  - stage:
    displayName: Build Stage
    jobs:
      - template: templates/build-sqldb.yml
        parameters:
          solutionName:  ControlDB
          buildPath:  elt-framework\ControlDB\bin\Release

  - stage: cd_nonprod
    jobs:
      - job:  Deploy
        steps:
          - task: AzureKeyVault@2
            displayName: Get keyvault secrets
            inputs:
              connectedServiceName: ba-devops-spn
              KeyVaultName: ba-keyvault1 
              SecretsFilter: ba-sqlserver1-sqlusername,ba-sqlserver1-password
              RunAsPreJob: true

          - task: DownloadPipelineArtifact@2
            inputs: 
              source: current
              artifactName: dacpac
              path: $(System.DefaultWorkingDirectory)

          - task: SqlAzureDacpacDeployment@1
            displayName: Deploy database
            inputs:
              ConnectedServiceNameARM: ba-devops-spn
              AuthenticationType: server
              ServerName: ba-sqlserver1.database.windows.net,1433
              DatabaseName: ControlDB
              SqlUsername: $(ba-sqlserver1-sqlusername)
              SqlPassword: $(ba-sqlserver1-password)
              DacpacFile: ControlDB.dacpac
              IpDetectionMethod: AutoDetect
              DeleteFirewallRule: true
              AdditionalArguments: /p:DropPermissionsNotInSource=false /p:DropRoleMembersNotInSource=false /p:DropObjectsNotInSource=true /p:IgnoreColumnOrder=true /p:IgnorePermissions=true




