parameters:
  solutionName:  Visual Studio Database solution Name
  buildPath: Folder where the dacpac will be built for instance repo/folder/bin/release/dbproject.dacpac


jobs:
- job:  
  displayName: Build and Publish dacpac 
  steps:
  - task: VSBuild@1
    displayName: Build database solution - ${{parameters.solutionName}}
    inputs:
      solution: '**\${{parameters.solutionName}}.sln'

  - publish: $(System.DefaultWorkingDirectory)/${{parameters.buildPath}}
    artifact: dacpac
    displayName: Publish Dacpac - ${{parameters.solutionName}}