parameters:
  solutionName:  Visual Studio Database solution Name
  buildPath: Folder where build files are available for e.g repo/folder/bin/release


jobs:
- job:  
  displayName: Build and Publish dacpac 
  steps:
  - task: VSBuild@1
    displayName: Build database solution - ${{parameters.solutionName}}
    inputs:
      solution: '**\${{parameters.solutionName}}.sln'

  - publish: $(System.DefaultWorkingDirectory)/${{parameters.buildPath}}
    artifact: dacpac
    displayName: Publish Dacpac - ${{parameters.solutionName}}